name: Context

on: [push, pull_request]

jobs:

  functions:
    runs-on: ubuntu-latest
    steps:
      - name: dump
        run: |
          echo ${{contains('hello', 'll')}}
          echo ${{startsWith('hello', 'he')}}
          echo ${{endsWith('hello', 'lo')}}
          echo ${{format('Hello {0}{1}{2}', 'World', '!', '!')}}
  
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: eccho '${{ toJSON(github) }}'
      - name: Dump job context
        if: failure() # job status function, return true if the previous step failed
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        if: always() # will always one doesn't matter what happened before
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'