name: Docker Container

on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container: 
      image: node:13.5.0-alpine3.10
      # ports:
      # volumes:
      # options:  --cpus 1 --host
    steps: # will run inside the container not the VM
      - name: Loge node node-version
        run: |
          node -v
          cat /etc/os-release
          