name: Docker Container

on:
  workflow_dispatch:
    inputs:
      my-input:
        type: string
        required: true
        default: "default"
        description: Input test

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container: 
      image: node:13.5.0-alpine3.10
      # ports:
      # volumes:
      # options:  --cpus 1 --host
    steps: # will run inside the container not the VM
      - name: Loge node node-version
        run: |
          node -v
          cat /etc/os-release
          echo The input is ${{inputs.my-input}}
