name: Commands


on: 
  pull_request:
    branches:
      - "dev"


jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    timeout-minutes: 360 # timeout limit
    steps:
      - name: echo
        run: echo "Hello"
        continue-on-error: true # if fails, other jobs will run
      - name: multiline script
        run: |
          npm -v
          node -v
      - name: use python Command
        run: |
          import platform
          print(platform.processor())
        shell: python # this should run on a python shell and not bash
  run-windows-commands:
    runs-on: windows-latest # default shell: powershell
    needs: ["run-shell-command"] # depends on the actions that specified into the list 
    steps:
      - name: dir powershell
        run: Get-Location
      - name: dir bash
        run: pwd
        shell: bash